from relateanything_runtime.config_keys import LOCKED_ARTIFACT_PINS

VALID_SUBMIT_BODY: dict = {
    "caseId": "case-1",
    "storedFileId": "file-1",
    "mimeType": "video/mp4",
    "sourceSignedUrl": "https://example.test/video.mp4",
    "processingConfigVersion": "cfg-v1",
    "runtimeRevision": "sha256:deadbeef",
    "processingConfiguration": {
        "content_visual_inference_relation_model": "maelic/relsgg-vits16plus",
        "content_visual_inference_relation_model_revision": LOCKED_ARTIFACT_PINS["relation_model_upstream_git"],
        "content_visual_inference_relation_model_weight_checksum": LOCKED_ARTIFACT_PINS["relation_model_weight_sha256"],
        "content_visual_inference_detector_model": "IDEA-Research/grounding-dino-base",
        "content_visual_inference_detector_revision": LOCKED_ARTIFACT_PINS["detector_revision"],
        "content_visual_inference_detector_weight_checksum": LOCKED_ARTIFACT_PINS["detector_weight_sha256"],
        "content_visual_inference_tracker_model": "ByteTrackTracker",
        "content_visual_inference_tracker_revision": LOCKED_ARTIFACT_PINS["tracker_publish_commit"],
        "content_visual_inference_runtime_container_revision": "sha256:deadbeef",
        "content_visual_inference_processing_config_version": "cfg-v1",
        "content_visual_inference_relation_vocabulary": '["beside","holding"]',
        "content_visual_inference_sampling_interval_ms": "1000",
        "content_visual_inference_max_frames": "8",
        "content_visual_inference_scene_change_threshold": "0.2",
        "content_visual_inference_motion_threshold": "0.1",
        "content_visual_inference_object_change_threshold": "0.1",
        "content_visual_inference_max_segments": "4",
        "content_visual_inference_max_objects_per_frame": "10",
        "content_visual_inference_min_detector_confidence": "0.35",
        "content_visual_inference_min_relation_confidence": "0.4",
        "content_visual_inference_tracking_config": "{}",
        "content_visual_inference_temporal_consolidation_window_ms": "500",
        "content_visual_inference_duplicate_suppression_config": "{}",
        "content_visual_inference_job_timeout_seconds": "120",
        "content_visual_inference_runtime_timeout_seconds": "90",
        "content_visual_inference_poll_interval_seconds": "30",
        "content_visual_inference_retry_count": "1",
        "content_visual_inference_retry_delay_seconds": "5",
        "content_visual_inference_concurrency_limit": "2",
        "content_visual_inference_cancellation_timeout_seconds": "30",
        "content_visual_inference_source_url_ttl_seconds": "600",
    },
}
