"""Governed processing configuration keys (must match Base API Management)."""

REQUIRED_PROCESSING_CONFIGURATION_KEYS: tuple[str, ...] = (
    "content_visual_inference_relation_model",
    "content_visual_inference_relation_model_revision",
    "content_visual_inference_relation_model_weight_checksum",
    "content_visual_inference_detector_model",
    "content_visual_inference_detector_revision",
    "content_visual_inference_detector_weight_checksum",
    "content_visual_inference_tracker_model",
    "content_visual_inference_tracker_revision",
    "content_visual_inference_runtime_container_revision",
    "content_visual_inference_processing_config_version",
    "content_visual_inference_relation_vocabulary",
    "content_visual_inference_sampling_interval_ms",
    "content_visual_inference_max_frames",
    "content_visual_inference_scene_change_threshold",
    "content_visual_inference_motion_threshold",
    "content_visual_inference_object_change_threshold",
    "content_visual_inference_max_segments",
    "content_visual_inference_max_objects_per_frame",
    "content_visual_inference_min_detector_confidence",
    "content_visual_inference_min_relation_confidence",
    "content_visual_inference_tracking_config",
    "content_visual_inference_temporal_consolidation_window_ms",
    "content_visual_inference_duplicate_suppression_config",
    "content_visual_inference_job_timeout_seconds",
    "content_visual_inference_runtime_timeout_seconds",
    "content_visual_inference_poll_interval_seconds",
    "content_visual_inference_retry_count",
    "content_visual_inference_retry_delay_seconds",
    "content_visual_inference_concurrency_limit",
    "content_visual_inference_cancellation_timeout_seconds",
    "content_visual_inference_source_url_ttl_seconds",
)

LOCKED_ARTIFACT_PINS = {
    "relation_model_upstream_git": "e9ea42aed60f766f12ad19d51709129c50110a3b",
    "relation_model_weight_sha256": "5d281bf0d89f2bbfd72ff5a14f9a40ce12534e790b0402e2ca970539c7bcc294",
    "detector_revision": "c0605c367b39f7589694dfcb61046322dc07ac4a",
    "detector_weight_sha256": "5548f844c928c4b6f411fa8cbcc2bfa8dbbba437cb1d513975519f93c2a9ed21",
    "tracker_package": "trackers==2.6.1",
    "tracker_wheel_sha256": "b5188de630f449958be3ce787fbb0375c69cfde094b6e4b4329cd79a98108501",
    "tracker_publish_commit": "3666546420b0fd564c8e63157a6621efffdfa01a",
}
